create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

create table contact
(
    id   bigint generated by default as identity,
    first_name varchar(200),
    last_name varchar(200),
    email_address varchar(200),
    phone_number varchar(200),
    comment varchar(200),
    company_id bigint,
    status varchar(200),
    created_date timestamp with time zone,
    last_modified_date timestamp with time zone,
    constraint pk_contact primary key (id)
);

create table my_user
(
    id   bigint generated by default as identity,
    created_date timestamp with time zone,
    last_modified_date timestamp with time zone,
    username varchar(200),
    password varchar(200),
    full_name varchar(200),
    enabled boolean,
    authorities bigint[],
    constraint pk_my_user primary key (id)
);

create table role
(
    id        bigint generated by default as identity,
    role_name varchar(200),
    constraint pk_role primary key (id)
);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

insert into role (role_name)
values ('USER'),
       ('ADMIN');

insert into my_user (username, password, full_name, enabled, authorities)
values ('username','password','fullName',true, array[1]::bigint[]);