create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

create table contact
(
    id   bigint generated by default as identity,
    first_name varchar(200),
    last_name varchar(200),
    email_address varchar(200),
    phone_number varchar(200),
    comment varchar(200),
    company_id bigint,
    status varchar(200),
    created_date timestamp with time zone,
    last_modified_date timestamp with time zone,
    constraint pk_contact primary key (id)
);

create table my_user
(
    id   bigint generated by default as identity,
    created_date timestamp with time zone,
    last_modified_date timestamp with time zone,
    username varchar(200) unique ,
    password varchar(200),
    full_name varchar(200),
    enabled boolean,
    role_id bigint,
    constraint pk_my_user primary key (id)
);

create table role
(
    id        bigint generated by default as identity,
    name varchar(200),
    privilege_id bigint,
    constraint pk_role primary key (id)
);

create table my_user_roles
(
    my_user_id bigint,
    role_id    bigint,
    constraint fk_my_user_id foreign key(my_user_id) references my_user(id),
    constraint fk_role_id foreign key(role_id) references role(id)
);

create table privilege
(
    id        bigint generated by default as identity,
    name varchar(200),
    constraint pk_privilege primary key (id)
);

create table role_privileges
(
    role_id    bigint,
    privilege_id bigint,
    constraint fk_role_id foreign key(role_id) references role(id),
    constraint fk_privilege_id foreign key(privilege_id) references privilege(id)
);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

insert into privilege (name)
values ('LIST'),
       ('CREATE'),
       ('MODIFY'),
       ('DELETE');

insert into role (name)
values ('ROLE_USER'),
       ('ROLE_ADMIN');


insert into role_privileges(role_id, privilege_id)
values (1,1),
       (2,1),
       (2,2),
       (2,3),
       (2,4);

