create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

create table contact
(
    id   bigint generated by default as identity,
    first_name varchar(200),
    last_name varchar(200),
    email_address varchar(200),
    phone_number varchar(200),
    comment varchar(200),
    company_id bigint,
    status varchar(200),
    created_date date,
    last_modified_date date,
    full_name varchar(200),
    constraint pk_contact primary key (id)
);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');
